import type { IProduct } from '@/types';
const products: IProduct[] = [
  {
    id: '1',
    title: 'Orange',
    img: 'https://nextui.org/images/fruit-1.jpeg',
    price: 5.5,
    stock: 2,
    categories: ['grocery'],
  },
  {
    id: '2',
    title: 'Tangerine',
    img: 'https://nextui.org/images/fruit-2.jpeg',
    price: 3.0,
    stock: 200,
    categories: ['grocery'],
  },
  {
    id: '3',
    title: 'Cherry',
    img: 'https://nextui.org/images/fruit-3.jpeg',
    price: 10.0,
    stock: 1,
    categories: ['grocery'],
  },
  {
    id: '4',
    title: 'Lemon',
    img: 'https://nextui.org/images/fruit-4.jpeg',
    price: 5.3,
    stock: 98,
    categories: ['grocery'],
  },
  {
    id: '5',
    title: 'Avocado',
    img: 'https://nextui.org/images/fruit-5.jpeg',
    price: 15.7,
    stock: 32,
    categories: ['grocery'],
  },
  {
    id: '6',
    title: 'Lemon 2',
    img: 'https://nextui.org/images/fruit-6.jpeg',
    price: 8.0,
    stock: 21,
    categories: ['grocery'],
  },
  {
    id: '7',
    title: 'Banana',
    img: 'https://nextui.org/images/fruit-7.jpeg',
    price: 7.5,
    stock: 10,
    categories: ['grocery'],
  },
  {
    id: '8',
    title: 'Watermelon',
    img: 'https://nextui.org/images/fruit-8.jpeg',
    price: 12.2,
    stock: 12,
    categories: ['grocery'],
  },
  {
    id: '9',
    title: 'Diaper',
    img: 'https://th.bing.com/th/id/R.7261bdbc1a6145aebef8cd17006a50da?rik=%2ffue3sd2HwgHZw&pid=ImgRaw&r=0',
    price: 23.2,
    stock: 120,
    categories: ['mom-and-baby'],
  },
  {
    id: '10',
    title: 'Pacifier',
    img: 'https://th.bing.com/th/id/OIP.yo05HPi7cHe9Fl45HouKgwHaHa?w=400&h=400&c=7&pcl=1b1a19&r=0&o=5&pid=1.7',
    price: 10.2,
    stock: 100,
    categories: ['mom-and-baby'],
  },
  {
    id: '11',
    title: 'Macbook pro 15inc 1TB 32GB RAM M1 CPU',
    img: 'https://th.bing.com/th/id/OIP.NKHexiC7S_fAxl3ih0tHRQHaHa?w=400&h=400&c=7&pcl=1b1a19&r=0&o=5&pid=1.7',
    price: 44000.9,
    stock: 100,
    categories: ['electronics'],
  },
  {
    id: '12',
    title:
      'Secret Outlast Clear Gel Antiperspirant Deodorant for Women, Protecting Powder, 3.4',
    img: 'https://th.bing.com/th/id/OIP._H99B3phDnFjbIaFcDXYIwHaHa?pid=ImgDet',
    price: 10.2,
    stock: 100,
    categories: ['personal-care'],
  },
];
export default products;
